# Generated by Django 3.2.6 on 2021-08-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, default='defualt.jpg', upload_to=''),
        ),
    ]
